search/urls.py
from django.urls import path

from . import views

app_name = 'search'
urlpatterns = [
    path('', views.index, name='index'),
    path('quintuple/', views.quintuple, name='quintuple'),
    path('<slug:doc_name>/', views.detail, name='detail')

]

searchengine/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('search.urls')),
    path('admin/', admin.site.urls),
]

search/models.py
from django.db import models

# Create your models here.

file/views.py
from django.shortcuts import render
from .script.delta_topi import main, delta_topi
from .script.text_bolding import main as change_text
from django.utils.safestring import mark_safe
from django.core.paginator import Paginator
import glob
import os
import time
# Create your views here.


def index(request):
    startT = time.time()
    if request.GET:
        result = []
        keys = request.GET['keywords']
        print("Keyword : "+(keys))
        jumlah = request.GET['jumlah'].split('-')
        temp = main(keys)
        if(temp != False):
            state, symbol, delta, start_state, final_state = main(keys)
        else:
            context = {
                'error': "Keyword yang anda masukan salah "}
            return render(request, 'search/index.html', context)
        list_text = sorted(glob.glob('docs/*.txt'),
                           key=lambda name: int(name[8:-4]))
        if(len(jumlah) == 1):
            for x in range(int(jumlah[0])):
                f = open(list_text[x], 'r', errors='ignore')
                content = f.read()
                f.close()
                data = delta_topi(content.lower(), state, symbol, delta,
                                  start_state, final_state)
                if data:
                    doc_name = list_text[x][5:-4]
                    text_res = content[int(data)-len(keys)+1:]
                    text_res = change_text(
                        text_res, keys.split(" "))
                    text_res = mark_safe(text_res)
                    result.append({'doc_name': doc_name, 'res': text_res})
            jumlah = jumlah[0]
        else:
            for x in range(int(jumlah[0]), int(jumlah[1])):
                f = open(list_text[x], 'r', errors='ignore')
                content = f.read()
                f.close()
                data = delta_topi(content.lower(), state, symbol, delta,
                                  start_state, final_state)
                if data:
                    doc_name = list_text[x][5:-4]
                    text_res = content[int(data)-len(keys)+1:]
                    text_res = change_text(text_res, keys.split(" "))
                    text_res = mark_safe(text_res)
                    result.append({'doc_name': doc_name, 'res': text_res})
            jumlah = "-".join(jumlah)
        if(len(result) != 0):
            page_num = request.GET.get('page', 1)
            paginator = Paginator(result, 5, allow_empty_first_page=True)
            page = paginator.get_page(page_num)
            context = {'data': page,
                       'keyword': request.GET['keywords'], 'jumlah': jumlah}
        else:
            context = {
                'error': "Tidak ditemukan document dengan keyword : "+keys}
        context['rtime'] = 'About %d results (%.2fms)' % (
            len(result), time.time() - startT)
        print("Runtime :" + str(time.time() - startT))
        return render(request, 'search/index.html', context)
    else:
        return render(request, 'search/index.html')


def detail(request, doc_name):

    f = open("docs/"+doc_name+".txt", 'r', errors='ignore')
    content = f.read()
    f.close()
    context = {'title': doc_name, 'data': content}
    return render(request, 'search/detail.html', context)


def quintuple(request):
    keys = request.GET['keyword']
    state, symbol, delta, start_state, final_state = main(keys)
    context = {'key': keys, 'state': state, 'symbol': symbol, 'delta': delta,
               'start_state': start_state, 'final_state': final_state}
    return render(request, 'search/quintuple.html', context)

search/views.py
from django.shortcuts import render
from .script.delta_topi import main, delta_topi
from .script.text_bolding import main as change_text
from django.utils.safestring import mark_safe
from django.core.paginator import Paginator
import glob
import os
import time
# Create your views here.


def index(request):
    startT = time.time()
    if request.GET:
        result = []
        keys = request.GET['keywords']
        print("Keyword : "+(keys))
        jumlah = request.GET['jumlah'].split('-')
        temp = main(keys)
        if(temp != False):
            state, symbol, delta, start_state, final_state = main(keys)
        else:
            context = {
                'error': "Keyword yang anda masukan salah "}
            return render(request, 'search/index.html', context)
        list_text = sorted(glob.glob('docs/*.txt'),
                           key=lambda name: int(name[8:-4]))
        if(len(jumlah) == 1):
            for x in range(int(jumlah[0])):
                f = open(list_text[x], 'r', errors='ignore')
                content = f.read()
                f.close()
                data = delta_topi(content.lower(), state, symbol, delta,
                                  start_state, final_state)
                if data:
                    doc_name = list_text[x][5:-4]
                    text_res = content[int(data)-len(keys)+1:]
                    text_res = change_text(
                        text_res, keys.split(" "))
                    text_res = mark_safe(text_res)
                    result.append({'doc_name': doc_name, 'res': text_res})
            jumlah = jumlah[0]
        else:
            for x in range(int(jumlah[0]), int(jumlah[1])):
                f = open(list_text[x], 'r', errors='ignore')
                content = f.read()
                f.close()
                data = delta_topi(content.lower(), state, symbol, delta,
                                  start_state, final_state)
                if data:
                    doc_name = list_text[x][5:-4]
                    text_res = content[int(data)-len(keys)+1:]
                    text_res = change_text(text_res, keys.split(" "))
                    text_res = mark_safe(text_res)
                    result.append({'doc_name': doc_name, 'res': text_res})
            jumlah = "-".join(jumlah)
        if(len(result) != 0):
            page_num = request.GET.get('page', 1)
            paginator = Paginator(result, 5, allow_empty_first_page=True)
            page = paginator.get_page(page_num)
            context = {'data': page,
                       'keyword': request.GET['keywords'], 'jumlah': jumlah}
        else:
            context = {
                'error': "Tidak ditemukan document dengan keyword : "+keys}
        context['rtime'] = 'About %d results (%.2fms)' % (
            len(result), time.time() - startT)
        print("Runtime :" + str(time.time() - startT))
        return render(request, 'search/index.html', context)
    else:
        return render(request, 'search/index.html')


def detail(request, doc_name):

    f = open("docs/"+doc_name+".txt", 'r', errors='ignore')
    content = f.read()
    f.close()
    context = {'title': doc_name, 'data': content}
    return render(request, 'search/detail.html', context)


def quintuple(request):
    keys = request.GET['keyword']
    state, symbol, delta, start_state, final_state = main(keys)
    context = {'key': keys, 'state': state, 'symbol': symbol, 'delta': delta,
               'start_state': start_state, 'final_state': final_state}
    return render(request, 'search/quintuple.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document Search</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-CuOF+2SnTUfTwSZjCXf01h7uYhfOBuxIhGKPbfEJ3+FqH/s6cIFN9bGr1HmAg4fQ"
      crossorigin="anonymous"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/search.js' %}" type="text/javascript"></script>
  </head>
  <body>
  {% include 'partials/_navbar.html' %}
    <div class="container">
      <div class="row">
        <div class="col-md mt-5 m-auto">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>

  </body>
</html>

templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-2">
	<div class="container">
		<a class="navbar-brand" href="/">Document Search</a>
	</div>
</nav>

templates/search/detail.html
{% extends 'base.html' %} 
{% block content %}
<h3>{{title}}</h3>
<p>{{data}}</p>
{% endblock %}

templates/search/index.html
{% extends 'base.html' %} 
{% block content %}

  <form action="" method="GET">

    <div class="input-group mb-3">
      <input type="text" required name="keywords" class="form-control" {% if data %} value="{{keyword}}" {% endif %} placeholder="Search Document" />
      <button class="btn btn-outline-info" type="submit" id="button-addon2">
        Search
      </button>
    </div>
    <div class="row justify-content-between">
    <div class="col-auto">
      {% if rtime %}
        <p class="text-muted">{{rtime}}</p>
      {% endif %}
    </div>
      <div class="row col-auto">
        <div class="col-auto"> 
        <label class="col-form-label" for="inputGroupSelect01">Jumlah Document</label>
        </div>
        <div class="col-auto "> 
          <select name="jumlah" {% if data %} onchange="changeData('/?keywords={{keyword}}&page={{data.number}}&jumlah=',this.value)" {% endif %} class="form-select" id="inputGroupSelect01">
            <option selected value="50" >50</option>
            <option {% if jumlah == "100" %} selected {% endif %}  value="100"  >100</option>
            <option {% if jumlah == "150" %} selected {% endif %}  value="150" >150</option>
            <option {% if jumlah == "200" %} selected {% endif %}  value="200" >200</option>
            <option {% if jumlah == "0-50" %} selected {% endif %}  value="0-50"  >0-50</option>
            <option {% if jumlah == "50-100" %} selected {% endif %}  value="50-100" >50-100</option>
            <option {% if jumlah == "100-150" %} selected {% endif %}  value="100-150" >100-150</option>
            <option {% if jumlah == "150-200" %} selected {% endif %}  value="100-150" >150-200</option>
          </select>
        </div>
      </div>
    </div>
  </form>

  {% if data %}
    {% for doc in data %}
        <div class="card p-2 m-4">
          <div class="card-body">
            <h4 class="card-title"><a href="{% url 'search:detail' doc.doc_name %}">{{ doc.doc_name }}</a></h4>
            <p class="card-text doc-snipet">{{ doc.res }}</p>
          </div>
        </div>
    {% endfor %}
    <div class="row my-3 mr-3 justify-content-between">
          <div class="col-auto ml-4">
            <a href="{% url 'search:quintuple' %}?keyword={{keyword}}" class="btn btn-primary">Lihat Quintuple</a>
          </div>
        <div class="col-auto">
          <ul class="pagination">
          {% if data.paginator.num_pages != 1 %}
            {% if data.has_previous %}
              <li class="page-item">
                <a href="{% url 'search:index' %}?keywords={{keyword}}&page=1&jumlah={{jumlah}}" class="page-link">First Page</a>
              </li>
            {% endif %}
              <li class="page-item {% if not data.has_previous %} active {% endif %} ">
                <a class="page-link "  href="{% url 'search:index' %}?keywords={{keyword}}&page={% if not data.has_previous %}{{data.number}}{% elif not data.has_next %}{{data.previous_page_number|add:"-1"}}{% else %}{{data.previous_page_number}}{% endif %}&jumlah={{jumlah}}">
                  {% if not data.has_previous %} 
                      {{data.number}} 
                  {% elif not data.has_next %} 
                      {{data.previous_page_number|add:"-1"}} 
                  {% else %}
                      {{data.previous_page_number}}
                  {% endif %}
                </a>
              </li>
              <li class="page-item {% if data.has_previous and data.has_next %}active{% endif %} ">
                <a class="page-link "  href="{% url 'search:index' %}?keywords={{keyword}}&page={% if data.has_previous and data.has_next %}{{data.number}}{% elif not data.has_previous %}{{data.next_page_number}}{% else %}{{data.previous_page_number}}{% endif %}&jumlah={{jumlah}}">
                  {% if data.has_previous and data.has_next %} 
                    {{data.number}} 
                  {% elif not data.has_previous %} 
                    {{data.next_page_number}} 
                  {% else %} 
                    {{data.previous_page_number}} 
                  {% endif %}
                </a>
              </li>
             <li class="page-item {% if not data.has_next %} active {% endif %} ">
              <a class="page-link "  href="{% url 'search:index' %}?keywords={{keyword}}&page={% if not data.has_next %}{{data.number}}{% elif not data.has_previous %}{{data.next_page_number|add:"1"}}{% else %}{{data.next_page_number}}{% endif %}&jumlah={{jumlah}}">
                {% if not data.has_next %} 
                    {{data.number}} 
                {% elif not data.has_previous %} 
                    {{data.next_page_number|add:"1"}} 
                {% else %}
                    {{data.next_page_number}}
                {% endif %}
              </a>
            </li>
            {% if data.has_next %}
              <li class="page-item">
                <a href="{% url 'search:index' %}?keywords={{keyword}}&page={{data.paginator.num_pages}}&jumlah={{jumlah}}" class="page-link">Last Page</a>
              </li>
            {% endif %}
          </ul>
          {% endif %}
        </div>
    </div>
     
  {% elif error %}
    <div class="alert alert-danger" role="alert">
    {{ error }}
    </div>
  {% endif %} 

{% endblock %}

templates/search/quintuple.html
{% extends 'base.html' %}
    {% block content %}
    <h3>Keyword : {{key}}</h3>
    <div class="card my-3">
       <h5 class="card-header">
        State
       </h5>
        <div class="card-body">
            <p class="card-text">{ {% for s in state %}{{s}}{% if not forloop.last %}, {% endif %}  {% endfor %} }</p>
        </div>
    </div>
    <div class="card my-3">
       <h5 class="card-header">
        Symbol
       </h5>
        <div class="card-body">
            <p class="card-text">{ {% for s in symbol %}{{s}}{% if not forloop.last %}, {% endif %}  {% endfor %} }</p>
        </div>
    </div>
     <div class="card my-3">
       <h5 class="card-header">
        Delta
       </h5>
        <div class="card-body">
            <ul>
                    {% for key,value in delta.items %}
                    {% if value|length > 1 %}
                        {% for k,s in value.items %}
                            <li>( {{key}},{{k}} ) = { {% for i in s %} {{i}} {% endfor %} }</li>
                        {% endfor %}
                    {% elif not value %}
                        <li>( {{key}} )</li>
                     {% else %}
                     <li>
                        {% for k , s in value.items %}
                                ( {{key}},{{k}} ) = { {{s}} }
                        {% endfor %}
                    </li>

                    {% endif %}

                {% endfor %}
            </ul>
        </div>
    </div>
     <div class="card my-3">
       <h5 class="card-header">
        Start State
       </h5>
        <div class="card-body">
            <p class="card-text">{{start_state}}</p>
        </div>
    </div>
      <div class="card my-3">
       <h5 class="card-header">
        Final State
       </h5>
        <div class="card-body">
        {% for k,s in final_state.items  %}
               <li>
               { {{k}} : {{s}} }
               </li> 
        {% endfor %}
        </div>
    </div>
    {% endblock content %}